########## XGBOOST #########
# Hispanic VS White
# ROS
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_no_age.json Settings/GroupFairnessParams/Hispanic_White_masked_age.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex_race.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_no_age.json Settings/GroupFairnessParams/Hispanic_White_masked_age.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex_race.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_no_age.json Settings/GroupFairnessParams/Hispanic_White_masked_age.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex_race.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_no_age_sex_race_best.json

#RUS
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_no_age.json Settings/GroupFairnessParams/Hispanic_White_masked_age.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex_race.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_no_age.json Settings/GroupFairnessParams/Hispanic_White_masked_age.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex_race.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_no_age.json Settings/GroupFairnessParams/Hispanic_White_masked_age.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex_race.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_no_age_sex_race_best.json

#Matched
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_no_age.json Settings/GroupFairnessParams/Hispanic_White_masked_age.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex_race.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_no_age.json Settings/GroupFairnessParams/Hispanic_White_masked_age.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex_race.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_no_age.json Settings/GroupFairnessParams/Hispanic_White_masked_age.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked_age_sex_race.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_no_age_sex_race_best.json

# Black VS White
# ROS
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_full.json Settings/GroupFairnessParams/Black_White.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_no_age.json Settings/GroupFairnessParams/Black_White_masked_age.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_no_age_sex.json Settings/GroupFairnessParams/Black_White_masked_age_sex.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_no_age_sex_race.json Settings/GroupFairnessParams/Black_White_masked_age_sex_race.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_full.json Settings/GroupFairnessParams/Black_White.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_no_age.json Settings/GroupFairnessParams/Black_White_masked_age.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_no_age_sex.json Settings/GroupFairnessParams/Black_White_masked_age_sex.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_no_age_sex_race.json Settings/GroupFairnessParams/Black_White_masked_age_sex_race.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_full.json Settings/GroupFairnessParams/Black_White.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_no_age.json Settings/GroupFairnessParams/Black_White_masked_age.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_no_age_sex.json Settings/GroupFairnessParams/Black_White_masked_age_sex.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_no_age_sex_race.json Settings/GroupFairnessParams/Black_White_masked_age_sex_race.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_no_age_sex_race_best.json

#RUS
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_full.json Settings/GroupFairnessParams/Black_White.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_no_age.json Settings/GroupFairnessParams/Black_White_masked_age.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_no_age_sex.json Settings/GroupFairnessParams/Black_White_masked_age_sex.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_no_age_sex_race.json Settings/GroupFairnessParams/Black_White_masked_age_sex_race.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_full.json Settings/GroupFairnessParams/Black_White.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_no_age.json Settings/GroupFairnessParams/Black_White_masked_age.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_no_age_sex.json Settings/GroupFairnessParams/Black_White_masked_age_sex.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_no_age_sex_race.json Settings/GroupFairnessParams/Black_White_masked_age_sex_race.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_full.json Settings/GroupFairnessParams/Black_White.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_no_age.json Settings/GroupFairnessParams/Black_White_masked_age.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_no_age_sex.json Settings/GroupFairnessParams/Black_White_masked_age_sex.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_no_age_sex_race.json Settings/GroupFairnessParams/Black_White_masked_age_sex_race.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_no_age_sex_race_best.json

#Matched
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_full.json Settings/GroupFairnessParams/Black_White.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_no_age.json Settings/GroupFairnessParams/Black_White_masked_age.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_no_age_sex.json Settings/GroupFairnessParams/Black_White_masked_age_sex.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_no_age_sex_race.json Settings/GroupFairnessParams/Black_White_masked_age_sex_race.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_full.json Settings/GroupFairnessParams/Black_White.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_no_age.json Settings/GroupFairnessParams/Black_White_masked_age.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_no_age_sex.json Settings/GroupFairnessParams/Black_White_masked_age_sex.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_no_age_sex_race.json Settings/GroupFairnessParams/Black_White_masked_age_sex_race.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_full.json Settings/GroupFairnessParams/Black_White.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_no_age.json Settings/GroupFairnessParams/Black_White_masked_age.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_no_age_sex.json Settings/GroupFairnessParams/Black_White_masked_age_sex.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_no_age_sex_race.json Settings/GroupFairnessParams/Black_White_masked_age_sex_race.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_no_age_sex_race_best.json



# Gender
# ROS
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_full.json Settings/GroupFairnessParams/Gender.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_no_age.json Settings/GroupFairnessParams/Gender_masked_age.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_no_age_sex.json Settings/GroupFairnessParams/Gender_masked_age_sex.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_fullset_no_age_sex_race.json Settings/GroupFairnessParams/Gender_masked_age_sex_race.json Settings/MLParams/tuning_fullsdoh_xgboost_ros_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_full.json Settings/GroupFairnessParams/Gender.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_no_age.json Settings/GroupFairnessParams/Gender_masked_age.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_no_age_sex.json Settings/GroupFairnessParams/Gender_masked_age_sex.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_contextual_no_age_sex_race.json Settings/GroupFairnessParams/Gender_masked_age_sex_race.json Settings/MLParams/tuning_contextual_xgboost_ros_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_full.json Settings/GroupFairnessParams/Gender.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_no_age.json Settings/GroupFairnessParams/Gender_masked_age.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_no_age_sex.json Settings/GroupFairnessParams/Gender_masked_age_sex.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-ROS-XG/tuning_individual_no_age_sex_race.json Settings/GroupFairnessParams/Gender_masked_age_sex_race.json Settings/MLParams/tuning_individual_xgboost_ros_gridcv_no_age_sex_race_best.json

#RUS
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_full.json Settings/GroupFairnessParams/Gender.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_no_age.json Settings/GroupFairnessParams/Gender_masked_age.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_no_age_sex.json Settings/GroupFairnessParams/Gender_masked_age_sex.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_fullset_no_age_sex_race.json Settings/GroupFairnessParams/Gender_masked_age_sex_race.json Settings/MLParams/tuning_fullsdoh_xgboost_rus_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_full.json Settings/GroupFairnessParams/Gender.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_no_age.json Settings/GroupFairnessParams/Gender_masked_age.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_no_age_sex.json Settings/GroupFairnessParams/Gender_masked_age_sex.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_contextual_no_age_sex_race.json Settings/GroupFairnessParams/Gender_masked_age_sex_race.json Settings/MLParams/tuning_contextual_xgboost_rus_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_full.json Settings/GroupFairnessParams/Gender.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_no_age.json Settings/GroupFairnessParams/Gender_masked_age.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_no_age_sex.json Settings/GroupFairnessParams/Gender_masked_age_sex.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-RUS-XG/tuning_individual_no_age_sex_race.json Settings/GroupFairnessParams/Gender_masked_age_sex_race.json Settings/MLParams/tuning_individual_xgboost_rus_gridcv_no_age_sex_race_best.json

#Matched
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_full.json Settings/GroupFairnessParams/Gender.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_no_age.json Settings/GroupFairnessParams/Gender_masked_age.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_no_age_sex.json Settings/GroupFairnessParams/Gender_masked_age_sex.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_fullset_no_age_sex_race.json Settings/GroupFairnessParams/Gender_masked_age_sex_race.json Settings/MLParams/tuning_fullsdoh_xgboost_match_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_full.json Settings/GroupFairnessParams/Gender.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_no_age.json Settings/GroupFairnessParams/Gender_masked_age.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_no_age_sex.json Settings/GroupFairnessParams/Gender_masked_age_sex.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_contextual_no_age_sex_race.json Settings/GroupFairnessParams/Gender_masked_age_sex_race.json Settings/MLParams/tuning_contextual_xgboost_match_gridcv_no_age_sex_race_best.json

sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_full.json Settings/GroupFairnessParams/Gender.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_fullvar_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_no_age.json Settings/GroupFairnessParams/Gender_masked_age.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_no_age_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_no_age_sex.json Settings/GroupFairnessParams/Gender_masked_age_sex.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_no_age_sex_best.json
sbatch slurm_assessment.sh model_assessment.py Settings/Tuning-Match-XG/tuning_individual_no_age_sex_race.json Settings/GroupFairnessParams/Gender_masked_age_sex_race.json Settings/MLParams/tuning_individual_xgboost_match_gridcv_no_age_sex_race_best.json


