###### Unfairness Mitigation Command : ADL-NN ######

sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/fml_adl_full.json Settings/GroupFairnessParams/Hispanic_White.json None
sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/fml_adl_no_age.json Settings/GroupFairnessParams/Hispanic_White.json None 
sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/fml_adl_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json None
sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/fml_adl_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White.json None

###### Unfairness Mitigation Command : XGBOOST ######

sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/fml_dir_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_fullset_gridcv_fullvar_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/fml_dir_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_fullset_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/fml_dir_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_fullset_gridcv_no_age_sex_best.json

sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/fml_cep_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_fullset_gridcv_fullvar_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/fml_cep_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_fullset_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/fml_cep_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_fullset_gridcv_no_age_sex_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/fml_cep_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked.json Settings/MLParams/xgboost_tuning_fullset_gridcv_no_age_sex_race_best.json

sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/contextual_fml_adl_full.json Settings/GroupFairnessParams/Hispanic_White.json None
sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/contextual_fml_adl_no_age.json Settings/GroupFairnessParams/Hispanic_White.json None
sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/contextual_fml_adl_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json None
sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/contextual_fml_adl_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White.json None

sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/contextual_fml_dir_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_contextual_gridcv_full_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/contextual_fml_dir_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_contextual_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/contextual_fml_dir_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_contextual_gridcv_no_age_sex_best.json

sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/contextual_fml_cep_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_contextual_gridcv_full_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/contextual_fml_cep_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_contextual_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/contextual_fml_cep_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_contextual_gridcv_no_age_sex_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/contextual_fml_cep_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked.json Settings/MLParams/xgboost_tuning_contextual_gridcv_no_age_sex_race_best.json

sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/individual_fml_adl_full.json Settings/GroupFairnessParams/Hispanic_White.json None
sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/individual_fml_adl_no_age.json Settings/GroupFairnessParams/Hispanic_White.json None
sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/individual_fml_adl_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json None
sbatch slurm_fairness_mitigation.sh fml_adversarial_debiasing.py Settings/FML/individual_fml_adl_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White.json None

sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/individual_fml_dir_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_individual_gridcv_full_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/individual_fml_dir_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_individual_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/individual_fml_dir_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_individual_gridcv_no_age_sex_best.json

sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/individual_fml_cep_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_individual_gridcv_full_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/individual_fml_cep_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_individual_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/individual_fml_cep_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/xgboost_tuning_individual_gridcv_no_age_sex_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/individual_fml_cep_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked.json Settings/MLParams/xgboost_tuning_individual_gridcv_no_age_sex_race_best.json

###### Unfairness Mitigation Command : LOGISTIC REGRESSION ######

sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/fml_dir_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_fullset_gridcv_fullvar_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/fml_dir_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_fullset_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/fml_dir_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_fullset_gridcv_no_age_sex_best.json

sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/fml_cep_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_fullset_gridcv_fullvar_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/fml_cep_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_fullset_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/fml_cep_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_fullset_gridcv_no_age_sex_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/fml_cep_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked.json Settings/MLParams/lrc_tuning_fullset_gridcv_no_age_sex_race_best.json

sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/contextual_fml_dir_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_contextual_gridcv_full_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/contextual_fml_dir_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_contextual_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/contextual_fml_dir_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_contextual_gridcv_no_age_sex_best.json

sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/contextual_fml_cep_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_contextual_gridcv_full_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/contextual_fml_cep_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_contextual_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/contextual_fml_cep_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_contextual_gridcv_no_age_sex_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/contextual_fml_cep_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked.json Settings/MLParams/lrc_tuning_contextual_gridcv_no_age_sex_race_best.json

sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/individual_fml_dir_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_individual_gridcv_full_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/individual_fml_dir_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_individual_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/individual_fml_dir_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_individual_gridcv_no_age_sex_best.json

sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/individual_fml_cep_full.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_individual_gridcv_full_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/individual_fml_cep_no_age.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_individual_gridcv_no_age_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/individual_fml_cep_no_age_sex.json Settings/GroupFairnessParams/Hispanic_White.json Settings/MLParams/lrc_tuning_individual_gridcv_no_age_sex_best.json
sbatch slurm_fairness_mitigation.sh fml_calibrated_eqodds_postprocessing.py Settings/FML/individual_fml_cep_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked.json Settings/MLParams/lrc_tuning_individual_gridcv_no_age_sex_race_best.json

#wrong experiment
#sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/contextual_fml_dir_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked.json Settings/MLParams/xgboost_tuning_contextual_gridcv_no_age_sex_race_best.json

#wrong experiment
#sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/fml_dir_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked.json Settings/MLParams/xgboost_tuning_fullset_gridcv_no_age_sex_race_best.json

#wrong experiment
#sbatch slurm_fairness_mitigation.sh fml_disparate_impact_remover.py Settings/FML/individual_fml_dir_no_age_sex_race.json Settings/GroupFairnessParams/Hispanic_White_masked.json Settings/MLParams/xgboost_tuning_individual_gridcv_no_age_sex_race_best.json
